spring.application.name=url-shortener

#mysql configuration
spring.datasource.url=jdbc:mysql://localhost:3306/url_shortener
spring.datasource.username=root
spring.datasource.password=Virat2020@#
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
